In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('creditcard.csv')

In [47]:
data.head()
data.shape

(284807, 31)

In [48]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [10]:
X = data.drop(columns=['Class'])
y = data['Class']

In [13]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [24]:
log_class = LogisticRegression()
paramgrid ={'C':10.0**np.arange(-2,3), 'penalty':['l1','l2']}
cv= KFold(n_splits=5, shuffle=False)

In [27]:
clr = GridSearchCV(log_class,paramgrid, cv=cv, n_jobs=-1, scoring='f1_macro') 
clr.fit(X_train, y_train)

C:\Users\anukatiy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\anukatiy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\anukatiy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [30]:
y_pred=clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9989817773252344
[[85260    34]
 [   53    96]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85294
           1       0.74      0.64      0.69       149

    accuracy                           1.00     85443
   macro avg       0.87      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [31]:
from sklearn.ensemble import RandomForestClassifier

rf_clr = RandomForestClassifier()
rf_clr.fit(X_train,y_train)

RandomForestClassifier()

In [32]:
y_pred=rf_clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9995084442259752
[[85287     7]
 [   35   114]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85294
           1       0.94      0.77      0.84       149

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



Observation: RandomforestClassfier has performed better and has no impact with the imbalanaced dataset

In [34]:
class_weight = dict({0:1,1:100})
# to increase weightage of lower class value count and check whether randomforestclassfier performs better

In [35]:
from sklearn.ensemble import RandomForestClassifier

rf_clr = RandomForestClassifier(class_weight=class_weight)
rf_clr.fit(X_train,y_train)
y_pred=rf_clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9995084442259752
[[85288     6]
 [   36   113]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85294
           1       0.95      0.76      0.84       149

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



Observation: There is no difference with application of class weigthage to randomforest classifier as it is small dataset.

In [41]:
!pip install imbalanced-learn --upgrade

     ---------------------------------------- 0.0/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----- ---------------------------------- 30.7/235.6 kB ? eta -:--:--
     ----------------- ------------------ 112.6/235.6 kB 211.6 kB/s eta 0:00:01
     --------------------- -------------- 143.4/235.6 kB 258.0 kB/s eta 0:00:01
     ------------------------------- ---- 204.8/235.6 kB 336.6 kB/s eta 0:00:01
     ----------------

In [ ]:
# Undersampling
from collections import Counter
from imblearn.under_sampling import NearMiss
ns= NearMiss(0.8)
X_train_ns,y_train_ns = ns.fit_smaple(X_train,y_train)
print("the no of classes before fit:", Counter(y_train))
print("the no of classes after fit:", Counter(y_train_ns))

In [ ]:
# Perform modeling on balanced dataset
rf_clr=RandomForestClassifier()
rf_clr.fit(X_train_ns,y_train_ns)

y_pred=rf_clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Over Sampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(0.6)
X_train_ns,y_train_ns =ros.fit_smaple(X_train,y_train)
print("the no of classes before fit:", Counter(y_train))
print("the no of classes after fit:", Counter(y_train_ns))

In [ ]:
# Perform modeling on balanced dataset using over sampling
rf_clr=RandomForestClassifier()
rf_clr.fit(X_train_ns,y_train_ns)

y_pred=rf_clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# SMOTE TOMEK

In [ ]:
from imblearn.combine import SMOTETomek

smot = SMOTETomek(0.75)
X_train_ns,y_train_ns =smot.fit_smaple(X_train,y_train)
rf_clr=RandomForestClassifier()
rf_clr.fit(X_train_ns,y_train_ns)


y_pred=rf_clr.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))